const request = require('supertest');
const { randomUUID } = require('crypto');
const { app } = require('../src/app');
const { db, pgp } = require('../src/db');
const { hashRequest } = require('../src/incidents');
const T1='11111111-1111-4111-8111-111111111111';
const T2='22222222-2222-4222-8222-222222222222';
const U='33333333-3333-4333-8333-333333333333';
const S='44444444-4444-4444-8444-444444444444';
const body={title:'API latency',severity:'P1',serviceId:S};
const post=(tenant=T1,key='key-1',b=body)=>request(app).post('/incidents').set('X-User-Id',U).set('X-Tenant-Id',tenant).set('Idempotency-Key',key).send(b);
async function count(table){ return +(await db.one(`SELECT count(*) AS n FROM ${table}`)).n; }
beforeAll(async()=>{ if(!(await db.one(`SELECT to_regclass('idempotency_keys') AS t`)).t) throw new Error('Run npm run db:reset after implementing schema.'); });
beforeEach(async()=>{ await db.none('TRUNCATE paging_jobs,idempotency_keys,incidents CASCADE'); });
afterAll(async()=>{ await pgp.end(); });
test('1 missing key returns 400 and no incident',async()=>{ const r=await request(app).post('/incidents').set('X-User-Id',U).set('X-Tenant-Id',T1).send(body); expect(r.status).toBe(400); expect(await count('incidents')).toBe(0); });
test('2 first request creates incident',async()=>{ expect((await post()).status).toBe(201); expect(await count('incidents')).toBe(1); });
test('3 sequential duplicate replays response',async()=>{ const a=await post(); const b=await post(); expect(b.status).toBe(201); expect(b.body.id).toBe(a.body.id); });
test('4 replay exposes replay header',async()=>{ await post(); const b=await post(); expect(b.headers['idempotent-replayed']).toBe('true'); });
test('5 changed body conflicts',async()=>{ await post(); const b=await post(T1,'key-1',{...body,title:'Different'}); expect(b.status).toBe(409); expect(b.body.error).toBe('idempotency_key_conflict'); });
test('6 same key across tenants is independent',async()=>{ await post(T1); await post(T2); expect(await count('incidents')).toBe(2); });
test('7 twenty concurrent duplicates create one incident',async()=>{ const rs=await Promise.all(Array.from({length:20},()=>post())); expect(rs.every(r=>r.status===201)).toBe(true); expect(await count('incidents')).toBe(1); });
test('8 concurrent duplicates create one paging job',async()=>{ await Promise.all(Array.from({length:20},()=>post())); expect(await count('paging_jobs')).toBe(1); });
test('9 lost-response retry produces one effect',async()=>{ await post(T1,'lost'); const retry=await post(T1,'lost'); expect(retry.status).toBe(201); expect(await count('incidents')).toBe(1); expect(await count('paging_jobs')).toBe(1); });
test('10 existing processing key does not execute',async()=>{ const h=hashRequest(body); await db.none(`INSERT INTO idempotency_keys(tenant_id,operation,key,request_hash,state,expires_at) VALUES($1,'POST:/incidents','busy',$2,'processing',now()+interval '1 hour')`,[T1,h]); const r=await post(T1,'busy'); expect(r.status).toBe(409); expect(r.body.error).toBe('operation_in_progress'); expect(await count('incidents')).toBe(0); });
test('11 existing failed key follows recovery contract',async()=>{ const h=hashRequest(body); await db.none(`INSERT INTO idempotency_keys(tenant_id,operation,key,request_hash,state,expires_at) VALUES($1,'POST:/incidents','failed',$2,'failed',now()+interval '1 hour')`,[T1,h]); const r=await post(T1,'failed'); expect(r.status).toBe(409); expect(r.body.error).toBe('prior_operation_failed'); });
test('12 transaction rollback removes all local writes',async()=>{ await expect(db.tx(async t=>{ await t.none(`INSERT INTO idempotency_keys(tenant_id,operation,key,request_hash,state,expires_at) VALUES($1,'x','rollback','h','processing',now()+interval '1 hour')`,[T1]); await t.none(`INSERT INTO incidents(tenant_id,service_id,title,severity) VALUES($1,$2,'x','P1')`,[T1,S]); throw new Error('forced'); })).rejects.toThrow('forced'); expect(await count('idempotency_keys')).toBe(0); expect(await count('incidents')).toBe(0); });
test('13 canonical hash ignores object property order',()=>{ expect(hashRequest({title:'x',severity:'P1',serviceId:S})).toBe(hashRequest({serviceId:S,title:'x',severity:'P1'})); });
test('14 operation and scope are stored exactly',async()=>{ await post(T1,'scope'); const row=await db.one(`SELECT tenant_id,operation,key FROM idempotency_keys`); expect(row.tenant_id).toBe(T1); expect(row.operation).toBe('POST:/incidents'); expect(row.key).toBe('scope'); });
